version: "3.9"
services:
  mongodb:
    container_name: mongo_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: apk-mirror
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/apk-mirror
      DB_NAME: apk-mirror
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=1

volumes:
  mongodb_data:
